---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfo: semver:~1.0
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: hazzindu/podinfo:1.0.5
        ports:
        - containerPort: 3000
